name: Build & Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            toolset: gcc
            platform_version: 22.04
            arch: x86
            boost_install_dir: /tmp/boost
          - os: macos-latest
            toolset: clang
            platform_version: 14
            arch: aarch64
            boost_install_dir: /tmp/boost
          - os: windows-latest
            toolset: msvc
            platform_version: 2022
            arch: x86
            boost_install_dir: C:\boost

    steps:
      - uses: actions/checkout@v4

      - name: Install boost
        uses: MarkusJx/install-boost@v2
        id: install-boost
        with:
          boost_version: 1.85.0
          toolset: ${{ matrix.toolset }}
          platform_version: ${{ matrix.platform_version }}
          arch: ${{ matrix.arch }}
          boost_install_dir: ${{ matrix.boost_install_dir }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest

      - name: Build wheel
        run: uv build
